In [2]:
import torch
import numpy as np
import time
device= "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [4]:
start_time=time.time()
zero=torch.zeros(1,1)
endtime=time.time()

time_spent=endtime-start_time
print(f"{time_spent:.4f}")

0.0010


In [11]:
%%time
torch_rand1=torch.rand(100,100,100,100).to(device)
torch_rand2=torch.rand(100,100,100,100).to(device)

np_rand1=torch.rand(100,100,100,100)
np_rand2=torch.rand(100,100,100,100)

start_time=time.time()

rand=(torch_rand1 @ torch_rand2)

endtime=time.time()

print(f"total time spend for {device} is {(endtime-start_time):.8f}")

start_time=time.time()

rand=np.multiply(np_rand1,np_rand2)
endtime=time.time()

print(f"total time spent for cpu is {(endtime-start_time):.8f}")

total time spend for cuda is 0.01000023
total time spent for cpu is 0.11475897
CPU times: total: 2.23 s
Wall time: 2.36 s


In [6]:
#defining a probablity distribution
probablities=torch.tensor([0.1,0.9])
#using multinomial distribution to have 10 samples
samples=torch.multinomial(probablities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [8]:
#to concatenate two tensors
tensor2=torch.tensor([1, 2, 3, 4])
output=torch.cat((tensor2, torch.tensor([5])), dim=0)
print(output)

tensor([1, 2, 3, 4, 5])


In [10]:
#to generate a lower triangle matrix 
output=torch.tril(torch.ones((5, 5)))
print(output)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [12]:
# to generate a upper triangle matrix
output=torch.triu(torch.ones(5,5))
print(output)

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [16]:
#generating a matrix on which after performing exponenting we get above result
output=torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
print(output)

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


In [17]:
#preforming exponent of above result
torch.exp(output)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
inputfile=torch.zeros(2, 3,4)
#below we swap the zero dimension with the 2nd dimension
output=inputfile.transpose(0, 2)
print(f"the shape of the input file is: {inputfile.shape}")
print(f"the sahpe of the output file is: {output.shape}")

the shape of the input file is: torch.Size([2, 3, 4])
the sahpe of the output file is: torch.Size([4, 3, 2])


In [19]:
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([5,6,7])
tensor3=torch.tensor([8,9,10])

#stacking the tensor along a new dimension
stacked=torch.stack([tensor1, tensor2, tensor3])
print(stacked)


tensor([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 8,  9, 10]])


In [23]:
import torch.nn as nn
# nn has learnable parameters
samples=torch.tensor([10.0,10.0, 10.0])
linear_nn=nn.Linear(3,3,bias=False)
print(linear_nn)
print(linear_nn(samples))

Linear(in_features=3, out_features=3, bias=False)
tensor([-4.2634, -9.1410, -3.3415], grad_fn=<SqueezeBackward4>)


In [26]:
import torch.nn.functional as ff
#create a tensor
samples=torch.tensor([10.0,10.0, 10.0])
#appling softmax function 
softmax_fun=ff.softmax(samples, dim=0)
print(softmax_fun)

tensor([0.3333, 0.3333, 0.3333])


In [27]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 1.7101, -1.0789, -0.4399,  0.2166,  2.9369, -0.2715],
        [-0.6008,  0.2324, -0.3845,  0.3382,  1.0286,  0.8563],
        [ 1.8161,  0.9672,  0.0688, -0.3312, -0.5676,  0.1047],
        [ 1.3587, -2.6485,  1.2132, -2.1391,  1.4979, -1.0197]],
       grad_fn=<EmbeddingBackward0>)
