In [1]:
import torch

In [3]:
randint=torch.randint(-100,100,(6,))
print(randint)

tensor([-82,  -7, -75, -46,   8,  47])


In [4]:
tensor=torch.tensor([[1,2,3],[3,6,1],[9,1,4]])
print(tensor)

tensor([[1, 2, 3],
        [3, 6, 1],
        [9, 1, 4]])


In [5]:
zeroes=torch.zeros(3,3)
print(zeroes)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
one=torch.ones(3,3)
print(one)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [8]:
arrange=torch.arange(5)
print(arrange)

tensor([0, 1, 2, 3, 4])


In [9]:
linespace=torch.linspace(3,10,steps=5)
print(linespace)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])


In [10]:
logspace=torch.logspace(start=-10, end=10, steps=5)
print(logspace)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])


In [11]:
eye=torch.eye(5)
print(eye)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [16]:
a=torch.empty((3,3), dtype=torch.int64)
emptylike=torch.empty_like(a)
print(emptylike)

tensor([[5967748073184,             0,             0],
        [            0,             0,             0],
        [            0,             0,             0]])
